### ISSUE TITLE
Error in  PrintPreview

### ISSUE THREAD

**Issue by maleczki** [DevExpress-Examples/Reporting_how-to-filter-entity-framework-data-source-tables-t571962#1]
![image](https://user-images.githubusercontent.com/7395067/140497707-92dfe1c1-ed8c-4948-a6a9-82acebc29055.png)

**Comment by ZhannaGaidukova** [comment]
Hello @maleczki,
I tested this project under DevExpress v21.2.4 and got no problem. Please share the complete stack trace, specify the version of DevExpress and the culture which you're running your application under.

I look forward to your reply.
